:lang: ja
:doctype: article
:nofooter:
:hardbreaks-option:

= マルチスレッド課題
ファイルツリーを走査して、目的のファイルを探索するマルチスレッドプログラムを作成してください

== 目的
. マルチスレッドによる並列化について学ぶ
. ファイルツリーの再帰的走査を経験する
. 低レイヤ関連のワードを調べることでバイナリアンの世界へいざなう

== 背景
「宇宙海賊派遣サービス」を運営するゴー☆ジャス社は、先月セキュリティインシデントによる情報漏えい事件が起きた。
ネットワーク機器のログには外部から侵入された形跡はなく、何らかの原因で機密情報を保存しているコンピュータである「マダガスカル」がウイルスに感染し、外部に情報が流出したと結論づけられた。
社内インフラ担当が実施したパケット解析結果によれば、機密情報が外部に流出する1週間前から定期的に「マダガスカル」が外部のサーバに対して「KimiNoHeartNi」という謎の文字列のHTTPリクエストを送信しており、情報流出が起きたときのみ外部のサーバから「Revolution!!!!!!」という文字列のレスポンスがあったことがわかった。
以上のことから「マダガスカル」が感染しているウイルスは外部サーバとやりとりし「Revolution!!!!!!」というコマンドをトリガーに動作することが予測される。
サーバ管理者である「コロンビアくん」はウイルス除去を上司から命じられたが、社内にはWindows用のウイルスソフトしかなくLinuxで動作している「マダガスカル」では動作しないことがわかった。


== 問題
コロンビアくんに変わって「マダガスカル」内に存在するウイルスをすべて探索するためのツールを作成してください。
本ツールのusageは以下とします。
gorgeous -p search-root-path -t number_of_worker_thread [-d]

=== オプション
-p search-root-path : ウイルスを探索する開始地点
-t number_of_worker_thread : workerスレッドの数
-d : デバッグ有効化

== 仕様

=== スキャン対象のファイル
探索開始ディレクトリは、引数として与えられたディレクトリとします。
ウイルスの特徴より、実行形式ファイル内に「KimiNoHeartNi」というマジックナンバーがあると考えられます。
そのため、stringsコマンドがバイナリファイルから文字列を探索する手法を参考に、マジックナンバーを内部に持つ実行形式ファイルを探索してください。
stringsコマンドは、内部でlibbfdというライブラリを使うことで、実行形式ファイルの場合はデータセグメントのみを文字列の探索対象としていますが、今回はそこまでやる必要はありません。

==== 実行形式ファイルの判定
Linux（その他の多くのUNIX OSも）の実行形式ファイルはELFというファイルフォーマットになっており、ELFではファイルの先頭52バイトがヘッダになっています。
ELFヘッダにはプログラムのエントリポイント（開始地点。実はCプログラムはmainから処理が開始されるわけではない）のアドレスやどのCPUアーキテクチャ向けの実行形式になっているのかなど様々な情報が詰められています。
今回の問題では、ELFヘッダの先頭4バイト（つまりファイル先頭4バイト）が「0x7f 0x45 0x4c 0x46」であれば、ELFであると判定してください。

=== 並列化について
実行形式ファイルが見つかるたびに、逐次処理でマジックナンバーをチェックするとプログラムの実行時間が問題になります。
Producer-Consumerパターンを参考にして、性能向上と拡張性を考慮した設計にしてください。

具体的には、以下の２つの種類のスレッドを作成し、これらの間をキューで繋ぐような設計にしてください。

. 実行形式ファイルの走査を行うスレッド
. マジックナンバーのチェック処理を行うスレッド（workerスレッド）

Producer-Consumerパターンでいうと、上記1がProducerに対応し、2がConsumerに対応します。
本プログラムは、1のスレッドがファイルツリー走査とELFファイルのチェックを行い、2のスレッドはマジックナンバーが含まれているか確認する構造にしてください。
この場合、2の処理はファイル全体を確認する必要ため、1のスレッドよりも処理に時間がかかることが予想されます。
そのため、ユーザから入力された数だけスレッドを生成し、高速に処理ができるように実装してください。
また、必要に応じて上記以外のスレッドを作成しても問題ありません。


=== 出力形式
以下の実行例のような出力を行なってください。

.実行例（正常終了）
----
./gorgeous -p test -t 5
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/dir_patch.o <1>
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/res_handle_limit.o
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/ref_stream.o
...
Number of files checked 982 <2>
Number of files scanned 29 <3>
Virus file path --> test/HDiffPatch/virus <4>
Virus file path --> test/HDiffPatch/dirDiffPatch/virus
Virus file path --> test/HDiffPatch/test/virus
----
<1> スキャンしたファイルのパス。（スキャンするのは、ELF形式のファイルのみにすることに注意）
<2> チェックしたファイルの数。ELF形式と非ELF形式のファイルの数。（openしたファイル数）
<3> スキャンしたELFファイルの数。
<4> マジックナンバーを含むファイル（ウイルス）のパス。

.実行例（ユーザキャンセルされた場合）
----
./gorgeous -p test -t 5 -d
2021/10/31 11:09:33.913705926 139869924386624 gorgeous_hoge.c:66           hoge started <1>
2021/10/31 11:09:33.913789827 139869899237120 gorgeous_piyo.c:175          piyo started
2021/10/31 11:09:33.913846148 139869899237120 gorgeous_fuga.c:264          fuga started
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/dir_patch.o
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/res_handle_limit.o
scanning --> test/HDiffPatch/dirDiffPatch/dir_patch/ref_stream.o
...
Number of files checked 948
Number of files scanned 15
Virus file path --> test/HDiffPatch/virus <2>
user canceled. <3>
----
<1> デバッグ出力。どのような情報をデバッグメッセージとするかは任意。フォーマットについては後述。
<2> ユーザキャンセルされるまでに見つけられたウイルスのファイルパス。
<3> ユーザキャンセルの場合は、「user canceled.」というメッセージを出力して終了すること。

=== エラーコード
エラーコードは、以下のものは含めてください。
ただし、必要に応じて各自で追加してもよいです。
また、正常終了の時は終了コードは0とし、エラー終了の場合は終了コードをエラーコードとしてください。
この場合、ユーザキャンセルはエラー終了として扱ってください。(つまりエラーコードを終了コードとし、エラーメッセージも出力してください)

.エラーコードテーブル
[cols="1,3", options="header"]
|===
|エラーコード
|エラーメッセージ
|1
|user canceled.
|2
|usage : gorgeous -p search_root_path -t number_of_worker_thread [-d]
|3
|memory allocation error.
|4
|library error. %s
|5
|system error. %s
|===


=== デバッグ出力
マルチスレッドで動作するアプリケーションは、競合状態など再現性のないバグが起こりやすく、またデバッグがしずらい特徴があります。
そのため、本プログラムではデバッグ出力を実装してください。デバッグ出力のフォーマットは以下のようにしてください。(nsecはナノ秒)
先頭からLINEまでをヘッダとし、ここは90バイトの左詰めにしてください。
また、ヘッダ+メッセージを合わせて512バイトにしてください。

----
yyyy/mm/dd HH/MM/SS.nsec thread_id FILENAME:LINE message
----

デバッグ出力のタイミングは任意としますが、障害発生時にトレースできるように最低限の出力は行なってください。

=== ユーザキャンセル
実行途中で処理をキャンセルできる機能（ユーザキャンセル）を実装してください。
ユーザキャンセルを受けた場合、速やかに各種処理を打ち切って終了してください。
ユーザキャンセルを受ける前に、既にウイルスを１つ以上見つけていた場合は、ウイルスのパスを出力してから終了してください。


== 制約
=== ファイルツリー走査の再帰処理について
ファイルツリーを走査する場合、再帰処理を使って実装されることがよくあります。
おそらくネットなどを参考にするとそのような実装が多く見つかるかと思います。
しかし、今回は再帰処理を用いずにファイルツリーの走査を実装してください。
再帰処理を用いない理由は、再帰処理はバグを生みやすいことと保守性が悪くなることおよび使用するスタックサイズのコントロールが難しいからです。
実際の開発でも再帰処理は基本的には使わないことをルールとしていることがあります。
再帰処理を使わずにファイルツリーを走査する方法は調べてみてください。

=== スレッドのキャンセル処理について
ユーザキャンセルを受けたときにスレッドをキャンセルする処理を実装することになりますが、pthread_cancelは使用しないでください。
pthread_cancelは遅延キャンセルを使ったとしても、実際にどこでキャンセルが行われるかが非決定的になるため、各種実装が難しくなるのと保守性が悪くなるためです。


== レビューポイントについて
本課題は、今までの課題と比べて難易度が高く、実装量もかなり多いのですべて実装してからレビューするのではなく、実装機能を分割してからレビューに出すようにしてください。
どの単位でレビューに出すかはレビュアと話し合って決めてください。

