:lang: ja
:doctype: book

= ソケットプログラミング課題

ネットワーク上のマシンAからマシンBへ、ソケット経由でファイル転送を行うプログラムを作成せよ

== usage

.サーバ起動
----
trans-data-server -p port [-s files-store-directory] [-d]
-p: 起動ポート番号
-s: 転送されたファイルを格納するディレクトリのパス
-d: デバッグモードを有効にする
----

.ファイル転送
----
trans-data-client -h hostname -p port -f filename [-d]
-h: サーバのホスト名 or IP address
-p: サーバが起動しているポート番号
-f: 転送するファイルのパス
-d: デバッグモードを有効にする
----


== サーバ実装

=== マルチクライアント対応
サーバが同時に複数のクライアントからファイルを受信できるようにするため、サーバ側はマルチプロセスまたはマルチスレッドで実装すること。 +
ちなみに解凍はマルチスレッドで作成しているが、HULFTはUNIX/Linuxはマルチプロセス、Windowsはマルチスレッドで実装されている。

==== 複数クライアントから同名のファイルを送られた場合
複数のクライアントから同時に同名のファイルを送信された場合、複数のクライアントが同じファイルに対して出力を行いファイル内容が破壊されてしまうため、これを防止する仕組みを実装すること。


=== 受信ファイル保存場所
クライアントから送信されたファイルは、サーバ起動時に「-s」オプションで指定されたディレクトリに出力すること。 +
サーバ起動時に「-s」オプションが指定されなかった場合、サーバを起動したディレクトリに出力する。

=== データサイズ検証
クライアントから送られてきたファイルを問題なく受信できているかを確認するため、送信開始時にクライアント送られてくる送信ファイルサイズとサーバ側で受信できたデータサイズを比較検証すること。
本来であれば、簡易的なハッシュを使って検証すべきだが、今回は実装を簡略化するためデータサイズのみで比較すればよい。


== サーバ/クライアント共通実装
=== デバッグモード
デバッグモードを有効にした場合は、サーバは起動したカレントディレクトリに実行ログを作成すること。 +
クライアントは、stderrにログを出力すること。 +
サーバはデーモン化する関係で制御端末を切り離すためファイル出力により対応するが、クライアントはデーモン化しないのとユーザビリティの観点からstrerrにログを出力すること。

出力フォーマットは以下のように先頭からLINEまでをヘッダとし、ここは90バイトの左詰め。
また、ヘッダ+メッセージを合わせて512バイトにする。

----
yyyy/mm/dd HH/MM/SS.nsec thread_id FILENAME:LINE message
----

=== タイムアウト
ネットワークを介したファイル転送を行うため、通信環境によっては接続断などが発生する可能性があるため、送受信タイムアウトと接続タイムアウト機能を実装すること。 +
タイムアウト値は、簡略化するため20秒で固定値としてよい。

=== 致命的エラーへの対処
メモリ確保エラーやシステムコールの想定外のエラー、タイムアウトなどプログラムをそれ以上正常に動作させることが難しくなった場合は、ピアに対してRSTパケットを送信してソケットを切断すること。
